### PR TITLE
Added 5cm/s and Shelter

### PR DESCRIPTION
**Pull request by Raventhicc**

### CODE REVIEW

**Comment by Soitora** [comment]
@RickDB @reconman How do we wanna handle movies in this?

**Comment by reconman** [comment]
I don't think the Plex movie agent even pulls data from TVDB movies. Instead, it mainly uses TMDB.

Since you need a seperate Plex library for anime movies, you'd have to run 2 PlexAniSyncs right now, one for your TV Anime library and one for your movie library.

Using seperate mapping files speeds up the script speed. So I would say map movies in a new TMDB movie mapping file.

**Comment by Soitora** [comment]
What about we name them (the mapping files) something like `movies_tmdb-en.yaml`? If they are gonna be remote files anyway

**Comment by reconman** [comment]
Sure, I don't have any strong opinions about it.

**Comment by Soitora** [comment]
@Raventhicc Can you move your edit in the PR to the newly created file for TMDB Movies?

**Comment by Raventhicc** [comment]
Sure, I'll do it tomorrow.

**Pull request closed without merging**
